name: InFocus

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup PHP
      uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1.5'
        extensions: mbstring, xml, bcmath
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with: 
        node-version: 18.14.2
    - uses: mirromutth/mysql-action@v1.1
      with:
        mysql database: infocus
        mysql user: infocus_admin
        mysql password: m7a18jQybrjjHhS
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Composer Dependencies
      run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader --no-dev
    - name: Install NPM Dependencies
      run: npm install
    - name: Build Assets
      run: npm run build
    - name: Generate Application Key
      run: php artisan key:generate
    - name: Create Storage Symlink
      run: php artisan storage:link
    - name: Set Directory Permissions
      run: chmod -R 775 storage bootstrap/cache
    - name: Create Database File
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Run Migrations
      run: php artisan migrate --force
    - name: Seed Database
      run: php artisan db:seed --force
    - name: Deploy to Hostinger via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./public/
        server-dir: /public_html/
    - name: Deploy Other Directories
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: /public_html/
        exclude: |
          .git*
          node_modules/
          vendor/
          public/
          storage/
    - name: Deploy Storage Directory
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./storage/
        server-dir: /public_html/storage/
        exclude: |
          .git*
          node_modules/
          vendor/
          public/
