name: InFocus

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1.5'
        extensions: mbstring, pdo, mysql
    - uses: actions/checkout@v4
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Update composer
      run: composer update
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: install npm
      run: npm install
    - name: build npm
      run: npm run build
    - name: Generate key
      run: php artisan key:generate
    - name: Storage link
      run: php artisan storage:link
   
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

      
    # - name: Run database migrations
    #   env:
    #     DB_USERNAME: ${{ secrets.DB_USERNAME }}
    #     DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    #     DB_DATABASE: ${{ secrets.DB_NAME }}
    #     DB_HOST: ${{ secrets.DB_HOST }}
    #   run: php artisan migrate --force

    # - name: Run database seeders
    #   env:
    #     DB_USERNAME: ${{ secrets.DB_USERNAME }}
    #     DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    #     DB_DATABASE: ${{ secrets.DB_NAME }}
    #     DB_HOST: ${{ secrets.DB_HOST }}
    #   run: php artisan db:seed --force
    # - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
    #   env:
    #     DB_CONNECTION: sqlite
    #     DB_DATABASE: database/database.sqlite
    #   run: php artisan test

    - name: Deploy to Hostinger via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: /public_html/
        exclude: |
          .git*
          node_modules/
          vendor/
          
    - name: Install Composer dependencies on server
      run: ssh -o StrictHostKeyChecking=no ${{ secrets.FTP_USERNAME }}@${{ secrets.FTP_SERVER }} "composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader"

    - name: Build assets on server
      run: ssh -o StrictHostKeyChecking=no ${{ secrets.FTP_USERNAME }}@${{ secrets.FTP_SERVER }} "npm install && npm run production"

    - name: Run storage link on server
      run: ssh -o StrictHostKeyChecking=no ${{ secrets.FTP_USERNAME }}@${{ secrets.FTP_SERVER }} "php artisan storage:link"

    - name: Run database migrations on server
      run: ssh -o StrictHostKeyChecking=no ${{ secrets.FTP_USERNAME }}@${{ secrets.FTP_SERVER }} "php artisan migrate --force"

    - name: Run database seeders on server
      run: ssh -o StrictHostKeyChecking=no ${{ secrets.FTP_USERNAME }}@${{ secrets.FTP_SERVER }} "php artisan db:seed --force"

